### ISSUE TITLE
[Idea] Boomstick that shoots buckshot.

### ISSUE THREAD

**Issue by DasIstVoltone** [RedstoneParadox/Tinkers-Arsenal#3]
Why buckshot? Because it is effective from a short distance and with an increase in this distance, the affected area increases, however, the greater the distance, the less hit, therefore, less damage per shot.

**Comment by RedstoneParadox** [comment]
I'm going to be honest, I only added the boomstick because I liked WoW at the time and I regret doing so as Tinker's Arsenal kinda has a reputation as a TiCon gun mod now. I really don't fancy adding more guns, sorry.
